version: '3.3'
services:
  mocktranet:
    image: nginx:latest
    volumes: 
      - ./web:/usr/share/nginx/html
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
